org.gradle.jvmargs=-Xmx4G --add-opens=java.base/java.lang=ALL-UNNAMED
org.gradle.daemon=false

mod_id=voxlink
mod_version=1.0.9-26.2
mod_group_id=icu.wuhui.voxlink
mod_license=LGPL-3.0

minecraft_version=26.2
neo_version=26.2.0.40-beta
minecraft_version_range=[26.2,26.3)
neo_version_range=[26.2,)
loader_version_range=[1,)
java_version=25
release_bytecode=25
