org.gradle.jvmargs=-Xmx4G --add-opens=java.base/java.lang=ALL-UNNAMED
org.gradle.daemon=false

mod_id=voxlink
mod_version=1.0.8-1.21.9_1.21.10
mod_group_id=icu.wuhui.voxlink
mod_license=LGPL-3.0

minecraft_version=1.21.10
neo_version=21.10.64
minecraft_version_range=[1.21.9,1.21.11)
neo_version_range=[21.9,)
loader_version_range=[1,)
java_version=21
release_bytecode=21
