pluginManagement {
    repositories {
        mavenLocal()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Minecraft libraries'
            url = 'https://libraries.minecraft.net'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

rootProject.name = "voxlink-neoforge-1.21.11"
